sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ainsleedocker/docker-react .

script:
  - docker run -e CI=true ainsleedocker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-234134328607"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: "master"





