version: '3'
services:
  web:
    build:
      context: .
#      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
